---
- name: Starting moloch setup
  include_tasks: "install_{{ ansible_distribution | lower }}_{{ ansible_distribution_version }}.yml"
  when: not moloch_uninstall

- name: Starting elasticsearch setup
  include_tasks: "configure_db.yml"
  when: not moloch_uninstall

- name: Starting moloch uninstaller
  include_tasks: "uninstall_{{ ansible_distribution | lower }}_{{ ansible_distribution_version }}.yml"
  when: moloch_uninstall
