---
- name: Ensure package moloch is deleted
  apt:
    name: moloch
    state: absent

- name: Remove entire installation directory 
  file:
    path: "{{ moloch_install_dir }}/"
    state: absent

- name: Get list of moloch systemd service files
  find:
    paths: /etc/systemd/system/
    patterns: moloch*
  register: moloch_systemd_files
  
- name: Ensure all moloch systemd files are deleted
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ moloch_systemd_files.files }}"
