---
- name: Restart molochcapture
  systemd:
    name: molochcapture
    enabled: true
    state: restarted
    daemon_reload: true

- name: Restart molochviewer
  systemd:
    name: molochviewer
    enabled: true
    state: restarted
    daemon_reload: true
